# Generated by Django 4.1.4 on 2022-12-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_link_created_at_link_updated_at_price_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.product'),
        ),
        migrations.AddField(
            model_name='price',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.link'),
        ),
    ]
