# Generated by Django 4.1.4 on 2022-12-17 07:54

from django.db import migrations, models
import scraper.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_link_product_price_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=scraper.models.product_directory_path),
        ),
    ]
